spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always

cloudinary:
  cloud-name: dgntwkoji
  api-key: 935149231195253
  api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: ${PORT:8080}